//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArtistAsset()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int ArtistAssetID { get; set; }
        public string ArtistName { get; set; }
        public string ArtistGenre { get; set; }
        public string ArtistPhoto { get; set; }
        public string ArtistBio { get; set; }
        public string ArtistID { get; set; }
        public string ArtistLink { get; set; }
    
        public virtual ArtistDetail ArtistDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
