//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public int OwnerStudioID { get; set; }
        public int ArtistAssetID { get; set; }
        public System.TimeSpan ReservationTime { get; set; }
    
        public virtual ArtistAsset ArtistAsset { get; set; }
        public virtual OwnerStudio OwnerStudio { get; set; }
    }
}
